import json
import os

def update_notebook():
    nb_path = "notebook/baseline.ipynb"
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    def fmt(lines):
        return [line + "\n" if not line.endswith("\n") else line for line in lines]

    # 1. Config (Index 3)
    nb['cells'][3]['source'] = fmt([
        "class Config:",
        "    DATA_ROOT = \"../data/train\"",
        "    IMG_HEIGHT = 64",
        "    IMG_WIDTH = 256",
        "    CHARS = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-\"",
        "    BATCH_SIZE = 64",
        "    LEARNING_RATE = 0.0003", # STABLE
        "    EPOCHS = 80",
        "    SEED = 42",
        "    NUM_FRAMES = 8",
        "    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')",
        "",
        "    CHAR2IDX = {char: idx + 1 for idx, char in enumerate(CHARS)}",
        "    IDX2CHAR = {idx + 1: char for idx, char in enumerate(CHARS)}",
        "    NUM_CLASSES = len(CHARS) + 1",
        "    VAL_SPLIT_FILE = \"val_tracks.json\"",
        "    TEST_SPLIT_FILE = \"test_tracks.json\"",
        "    VAL_SIZE = 2000",
        "    TEST_SIZE = 2000"
    ])

    # 2. Architecture (Index 11) - Update Dropout to 0.15
    nb['cells'][11]['source'] = fmt([
        "class PositionalEncoding(nn.Module):",
        "    def __init__(self, d_model, max_len=500):",
        "        super().__init__()",
        "        pe = torch.zeros(max_len, d_model)",
        "        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)",
        "        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))",
        "        pe[:, 0::2] = torch.sin(position * div_term)",
        "        pe[:, 1::2] = torch.cos(position * div_term)",
        "        self.register_buffer('pe', pe.unsqueeze(0))",
        "",
        "    def forward(self, x):",
        "        return x + self.pe[:, :x.size(1)]",
        "",
        "class HybridAttentionFusion(nn.Module):",
        "    def __init__(self, channels):",
        "        super().__init__()",
        "        self.temporal_pool = nn.AdaptiveAvgPool2d(1)",
        "        self.temporal_gate = nn.Sequential(",
        "            nn.Linear(channels, channels // 4),",
        "            nn.ReLU(True),",
        "            nn.Linear(channels // 4, 1),",
        "            nn.Sigmoid()",
        "        )",
        "        self.spatial_net = nn.Sequential(",
        "            nn.Conv2d(channels * 2, channels // 2, 3, 1, 1),",
        "            nn.BatchNorm2d(channels // 2),",
        "            nn.ReLU(True),",
        "            nn.Conv2d(channels // 2, 1, 3, 1, 1)",
        "        )",
        "        self.channel_gate = nn.Sequential(",
        "            nn.AdaptiveAvgPool2d(1),",
        "            nn.Conv2d(channels, channels // 4, 1),",
        "            nn.ReLU(True),",
        "            nn.Conv2d(channels // 4, channels, 1),",
        "            nn.Sigmoid()",
        "        )",
        "        self._init_weights()",
        "",
        "    def _init_weights(self):",
        "        for m in self.modules():",
        "            if isinstance(m, nn.Conv2d):",
        "                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')",
        "            elif isinstance(m, nn.Linear):",
        "                nn.init.normal_(m.weight, 0, 0.01)",
        "",
        "    def forward(self, x, t):",
        "        bt, c, h, w = x.size()",
        "        b = bt // t",
        "        x_view = x.view(b, t, c, h, w)",
        "        pooled = self.temporal_pool(x).view(bt, c)",
        "        t_weights = self.temporal_gate(pooled).view(b, t, 1, 1, 1)",
        "        ref_idx = t // 2",
        "        ref = x_view[:, ref_idx:ref_idx+1].repeat(1, t, 1, 1, 1)",
        "        concat_feat = torch.cat([x_view, ref], dim=2).view(bt, c*2, h, w)",
        "        s_scores = self.spatial_net(concat_feat).view(b, t, 1, h, w)",
        "        combined_scores = s_scores * t_weights",
        "        att_map = F.softmax(combined_scores, dim=1)",
        "        fused = torch.sum(x_view * att_map, dim=1)",
        "        c_att = self.channel_gate(fused)",
        "        return fused * c_att",
        "",
        "class MultiFrameCRNN(nn.Module):",
        "    def __init__(self, num_classes, d_model=512):",
        "        super().__init__()",
        "        backbone_model = convnext_tiny(weights=ConvNeXt_Tiny_Weights.DEFAULT)",
        "        self.backbone = backbone_model.features",
        "        self.conv_proj = nn.Sequential(",
        "            nn.Upsample(scale_factor=(1, 4), mode='bilinear', align_corners=True),",
        "            nn.Conv2d(768, d_model, kernel_size=(3, 3), stride=(2, 1), padding=(1, 1)),",
        "            nn.BatchNorm2d(d_model),",
        "            nn.ReLU()",
        "        )",
        "        self.fusion = HybridAttentionFusion(channels=d_model)",
        "        self.pos_encoder = PositionalEncoding(d_model=d_model)",
        "        encoder_layer = nn.TransformerEncoderLayer(",
        "            d_model=d_model, nhead=8, dim_feedforward=d_model*4, dropout=0.15, batch_first=True", # USER PREF
        "        )",
        "        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=6)",
        "        self.fc = nn.Linear(d_model, num_classes)",
        "",
        "    def freeze_backbone(self, freeze=True):",
        "        for param in self.backbone.parameters():",
        "            param.requires_grad = not freeze",
        "        print(f\"❄️ ConvNeXt Backbone: {'Frozen' if freeze else 'Unfrozen'}\")",
        "",
        "    def forward(self, x):",
        "        b, t, c, h, w = x.size()",
        "        x = x.view(b * t, c, h, w)",
        "        features = self.backbone(x)",
        "        features = self.conv_proj(features)",
        "        fused = self.fusion(features, t)",
        "        fused = F.adaptive_avg_pool2d(fused, (1, None))",
        "        seq = fused.squeeze(2).permute(0, 2, 1)",
        "        seq = self.pos_encoder(seq)",
        "        out = self.transformer(seq)",
        "        out = self.fc(out)",
        "        return out.log_softmax(2)"
    ])

    # 3. Training Loop (Index 14) - Update Clip, Weight Decay, OneCycleLR
    nb['cells'][14]['source'] = fmt([
        "def train_pipeline():",
        "    seed_everything(Config.SEED)",
        "    train_ds = AdvancedMultiFrameDataset(Config.DATA_ROOT, mode='train')",
        "    val_ds = AdvancedMultiFrameDataset(Config.DATA_ROOT, mode='val')",
        "    train_loader = DataLoader(train_ds, batch_size=Config.BATCH_SIZE, shuffle=True, collate_fn=AdvancedMultiFrameDataset.collate_fn, num_workers=4, pin_memory=True)",
        "    val_loader = DataLoader(val_ds, batch_size=Config.BATCH_SIZE, shuffle=False, collate_fn=AdvancedMultiFrameDataset.collate_fn, num_workers=4) if val_ds else None",
        "",
        "    model = MultiFrameCRNN(num_classes=Config.NUM_CLASSES).to(Config.DEVICE)",
        "    criterion = nn.CTCLoss(blank=0, zero_infinity=True)",
        "    optimizer = optim.AdamW(model.parameters(), lr=Config.LEARNING_RATE, weight_decay=1e-3)", # STABLE
        "    scheduler = optim.lr_scheduler.OneCycleLR(optimizer, max_lr=Config.LEARNING_RATE, steps_per_epoch=len(train_loader), epochs=Config.EPOCHS, pct_start=0.3, div_factor=25.0)",
        "    scaler = GradScaler()",
        "    best_acc = 0.0",
        "",
        "    for epoch in range(Config.EPOCHS):",
        "        if epoch < 5:",
        "            model.freeze_backbone(True)",
        "        else:",
        "            should_freeze = np.random.random() < 0.3",
        "            model.freeze_backbone(should_freeze)",
        "",
        "        model.train()",
        "        epoch_loss = 0",
        "        pbar = tqdm(train_loader, desc=f\"Ep {epoch+1}/{Config.EPOCHS}\")",
        "        for images, targets, target_lengths, _ in pbar:",
        "            images, targets, target_lengths = images.to(Config.DEVICE), targets.to(Config.DEVICE), target_lengths.to(Config.DEVICE)",
        "            optimizer.zero_grad(set_to_none=True)",
        "            ",
        "            lam = np.random.beta(1.0, 1.0) if random.random() < 0.3 else 1.0",
        "            if lam < 1.0:",
        "                idx = torch.randperm(images.size(0)).to(Config.DEVICE)",
        "                images = lam * images + (1 - lam) * images[idx]",
        "            ",
        "            with autocast('cuda'):",
        "                preds = model(images)",
        "                loss = criterion(preds.permute(1, 0, 2), targets, torch.full((images.size(0),), preds.size(1), dtype=torch.long), target_lengths)",
        "            ",
        "            scaler.scale(loss).backward()",
        "            scaler.unscale_(optimizer)",
        "            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)", # STABLE CLIP
        "            scaler.step(optimizer)",
        "            scaler.update()",
        "            scheduler.step()",
        "            epoch_loss += loss.item()",
        "            pbar.set_postfix({'loss': loss.item()})",
        "",
        "        if val_loader:",
        "            model.eval()",
        "            correct, total = 0, 0",
        "            with torch.no_grad():",
        "                for images, targets, target_lengths, labels in val_loader:",
        "                    preds = model(images.to(Config.DEVICE))",
        "                    decoded = decode_predictions(preds, Config.IDX2CHAR)",
        "                    for p, g in zip(decoded, labels):",
        "                        if p == g: correct += 1",
        "                        total += 1",
        "            val_acc = (correct / total) * 100",
        "            print(f\"Result: Train Loss: {epoch_loss/len(train_loader):.4f} | Val Acc: {val_acc:.2f}%\")",
        "            if val_acc > best_acc:",
        "                best_acc = val_acc",
        "                torch.save(model.state_dict(), \"best_model.pth\")"
    ])

    with open(nb_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print(f"✨ Successfully applied ultimate stability fixes to {nb_path}.")

if __name__ == "__main__":
    update_notebook()
